version: '3.8'

services:
  chezmoi-tui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chezmoi-tui
    volumes:
      # Mount the chezmoi source directory
      - ~/.local/share/chezmoi:/home/nobody/.local/share/chezmoi:rw
      # Mount the destination directory (your home directory)
      - ~:/home/nobody:rw
      # Mount SSH keys if needed for git operations
      - ~/.ssh:/home/nobody/.ssh:ro
      # Mount git configuration
      - ~/.gitconfig:/home/nobody/.gitconfig:ro
    environment:
      - HOME=/home/nobody
      - CHEZMOI_SOURCE_PATH=/home/nobody/.local/share/chezmoi
      - CHEZMOI_DEST_PATH=/home/nobody
    working_dir: /home/nobody
    stdin_open: true
    tty: true
    command: ["chezmoi-tui", "tui"]
    
  chezmoi-tui-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chezmoi-tui-web
    # This could be extended to run a web interface in the future
    command: ["sleep", "infinity"]
    # Additional configuration would be needed for a web interface