name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.x

    - name: Create release archive
      run: |
        mkdir -p dist
        GOOS=linux GOARCH=amd64 go build -o dist/chezmoi-tui-linux-amd64 .
        GOOS=linux GOARCH=arm64 go build -o dist/chezmoi-tui-linux-arm64 .
        GOOS=darwin GOARCH=amd64 go build -o dist/chezmoi-tui-darwin-amd64 .
        GOOS=darwin GOARCH=arm64 go build -o dist/chezmoi-tui-darwin-arm64 .
        GOOS=windows GOARCH=amd64 go build -o dist/chezmoi-tui-windows-amd64.exe .
        
    - name: Calculate checksums
      run: |
        cd dist && sha256sum * > checksums.txt && cd ..

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          dist/chezmoi-tui-linux-amd64
          dist/chezmoi-tui-linux-arm64
          dist/chezmoi-tui-darwin-amd64
          dist/chezmoi-tui-darwin-arm64
          dist/chezmoi-tui-windows-amd64.exe
          dist/checksums.txt
        generate_release_notes: true